org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.3.22
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=ashenprotocol
mod_name=Ashen Protocol
mod_license=MIT
mod_version=0.3.0

mod_group_id=dev.yuni.ashenprotocol
mod_authors=yuniaries
mod_description=Original expedition and restoration gameplay with Lost Coordinates, six ruins, four guardians, processing machines, tiered equipment and protocol networks.
